### ISSUE TITLE
Add banner with request for beta pilot testers in lesson website

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/lesson-gpu-programming#107]
Similar to:
<img width="605" alt="image" src="https://github.com/carpentries-incubator/lesson-gpu-programming/assets/9945255/aa9993c6-846c-47d7-a919-ee0896a8ac95">

**Comment by isazi** [comment]
Is there a standard template for this, something we can easily enable?

**Comment by svenvanderburg** [comment]
@isazi no sorry, there is no standard template. But you can add something like this to `index.md`:

::: callout
## Do you want to teach this lesson?
Do you want to teach GPU programming? This material is open-source and freely available. Are you planning on using our material in your teaching? Send us an email at training@esciencecenter.nl. We would love to help you prepare to teach the lesson and receive feedback on how it could be further improved, based on your experience in the workshop.
:::

**Comment by svenvanderburg** [comment]
I went ahead and created a PR
