### ISSUE TITLE
Review "Episode 3: Your First GPU Kernel"

### ISSUE THREAD

**Issue by isazi** [carpentries-incubator/lesson-gpu-programming#11]
We have a first draft of episode 3.

For your convenience, you can access the [rendered episode here](https://carpentries-incubator.github.io/lesson-gpu-programming/03-first_program/index.html).

Please provide comments here, or submit a pull request and reference this issue.

**Comment by JensWehner** [comment]
Hi I would remove the `%` in the code, because it makes copying snippets much harder. I am also not used to reading code with the `%` in front.

**Comment by JensWehner** [comment]
Do you want to include more vendors than just NVIDIA? I mean I am not sure how well this lesson will age in a couple of years. It also goes a bit against FOSS to lock in on one vendor.

**Comment by JensWehner** [comment]
I think my comments are too generic and not for episode 3 only.

**Comment by jiskattema** [comment]
Explain that ```__global__``` is also an ```execution space specifier```
```
This is the definition of our CUDA vector_add function. The __global__ keyword is specific to CUDA, and all the definitions of our kernels will be preceded by this keyword. What the keyword means is that the defined function will run on the GPU, but can be called from the host (the Python interpreter running on the CPU, in our case), and in some cases also from the GPU itself.
```

**Comment by jiskattema** [comment]
Suggestion for key points:
* start kernels definitions with ```extern "C" __global__ ```
* CUDA uses ```gridDim, blockIdx, blockDim, threadIdx``` to tell your kernel about the parallelization.

**Comment by isazi** [comment]
Thanks @jiskattema I have changed the two paragraphs about the identifiers with the following:

```
This is the definition of our CUDA `vector_add` function.
The `__global__` keyword is an execution space identifier, and it is specific to CUDA.
What this keyword means is that the defined function will be able to run on the GPU, but can also be called from the host (in our case the Python interpreter running on the CPU).
All of our kernel definitions will be preceded by this keyword.

Other execution space identifiers in CUDA-C are `__host__`, and `__device__`.
Functions annotated with the `__host__` identifier will run on the host, and be only callable from the host, while functions annotated with the `__device__` identifier will run on the GPU, but can only be called from the GPU itself.
We are not going to use these identifiers as often as `__global__`.
```

**Comment by isazi** [comment]
> Suggestion for key points:
> 
>     * start kernels definitions with `extern "C" __global__ `
> 
>     * CUDA uses `gridDim, blockIdx, blockDim, threadIdx` to tell your kernel about the parallelization.

Used them for keypoints.
