### ISSUE TITLE
Explain convolution

### ISSUE THREAD

**Issue by isazi** [carpentries-incubator/lesson-gpu-programming#29]
In episode 2 (CuPy) we use a convolution operation on an image to explain CuPy. We need a sentence or two to explain what the convolution operation is.

**Comment by Codemonk-adi** [comment]
Would like to work on this issue, have experience in deep learning models including Convolution models

**Comment by isazi** [comment]
Sure, let me know if you write something.

**Comment by Codemonk-adi** [comment]
The Convolution Operation takes an input image and a feature detector(i.e, filter). The feature detector is placed on the input image and dot product of the feature detector and the overlapping image is calculated.

The filter is then slid across the image mapping it into a resultant output image.i.e, the output of the convolution Operation

**Comment by Codemonk-adi** [comment]
let me if know if this is okay and may I be assigned for the other issues as well?

**Comment by isazi** [comment]
Send me a pull request for this change and I'll review and approve it.

**Comment by MaciejWas** [comment]
Hi, I think that for convolutions it would be best to provide some sort of visualization. There are tons of those such as
[this one](https://commons.wikimedia.org/wiki/File:2D_Convolution_Animation.gif). Why not include it (of course with crediting the author) ?

**Comment by isazi** [comment]
This is also a good idea @MaciejWas

**Comment by isazi** [comment]
After all the contributions, I think we can close this issue.
