### ISSUE TITLE
Create an image of CPU-GPU system

### ISSUE THREAD

**Issue by isazi** [carpentries-incubator/lesson-gpu-programming#31]
We need an image as a visual aid to show that CPU and GPU are two separate systems, connected by a bus, with each its own memory.

The image should have the right copyright to be used in the lesson and distributed with the lesson.

**Comment by HannoSpreeuw** [comment]
![afbeelding](https://user-images.githubusercontent.com/11661087/135823528-82bd73af-fe0d-4029-b0b6-9c41b599fd21.png)
Something like this?
(from slides from you and Ben van Werkhoven).

**Comment by isazi** [comment]
Yeah something like that
