### ISSUE TITLE
Speedup with shared memory

### ISSUE THREAD

**Issue by isazi** [carpentries-incubator/lesson-gpu-programming#63]
Show how using shared memory helps speed up the histogram in the lesson material.

**Comment by isazi** [comment]
Looks like on the GPU we tested the code, the histogram is already fast enough without using shared memory.

**Comment by isazi** [comment]
It would be better to refactor the code to run all the versions one after the other on the same data.

**Comment by HannoSpreeuw** [comment]
How do you define fast enough?
Can you still achieve speedups from using shared memory with large enough histograms?

**Comment by isazi** [comment]
> How do you define fast enough?

Not using shared memory seems faster than using shared memory on Google Colab. I need to investigate if this is because of measurement precision (runtime is very fast anyway), or because of something else.

> Can you still achieve speedups from using shared memory with large enough histograms?

I am using 2ˆ20 input arrays, large enough for the CPU to take over a minute.

**Comment by HannoSpreeuw** [comment]
Wow. I did not expect that.
What is the GPU runtime?

**Comment by isazi** [comment]
Few microseconds.

**Comment by HannoSpreeuw** [comment]
Okay. Yeah, a longer runtime would be somewhat better, would require even larger input.
