### ISSUE TITLE
Missing dependency for non-Colab Setup

### ISSUE THREAD

**Issue by Sparrow0hawk** [carpentries-incubator/lesson-gpu-programming#94]
Hi 👋

I'm testing out this code in advance of a workshop running this lesson. We're using a different system to colab and I noticed that `matplotlib` is missing as a dependency in the [setup](https://carpentries-incubator.github.io/lesson-gpu-programming/setup.html) section.

```python
import pylab as pyl

# Necessary command to render a matplotlib image in a Jupyter notebook.

%matplotlib inline

# Display the image

# You can zoom in using the menu in the window that will appear

pyl.imshow(deltas[0:32, 0:32])

pyl.show()
```
​
```err
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 1
----> 1 import pylab as pyl
      2 # Necessary command to render a matplotlib image in a Jupyter notebook.
      3 get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'pylab'
```

After installing `matplotlib` this issue went away. I'll raise a PR and suggest it back.

**Comment by Sparrow0hawk** [comment]
Just to note I discovered this setting up my environment with conda but assume the same will be true of pip.

**Comment by isazi** [comment]
Thanks, I guess that both on Colab and the system we use usually to teach this course matplotlib is installed and we never noticed.

**Comment by Sparrow0hawk** [comment]
Also found that `scipy` is missing:

```python
from scipy.signal import convolve2d as convolve2d_cpu

convolved_image_using_CPU = convolve2d_cpu(deltas, gauss)

pyl.imshow(convolved_image_using_CPU[0:32, 0:32])

pyl.show()
```
```error
%timeit -n 1 -r 1 convolve2d_cpu(deltas, gauss)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[13], line 1
----> 1 from scipy.signal import convolve2d as convolve2d_cpu
      3 convolved_image_using_CPU = convolve2d_cpu(deltas, gauss)
      4 pyl.imshow(convolved_image_using_CPU[0:32, 0:32])

ModuleNotFoundError: No module named 'scipy'
```

**Comment by Sparrow0hawk** [comment]
I'm still working through the lesson so will get through everything post what I find here and submit a more fulsome PR!

**Comment by Sparrow0hawk** [comment]
`astropy` is also missing for [real world example section](https://carpentries-incubator.github.io/lesson-gpu-programming/02-cupy/index.html#a-real-world-example-image-processing-for-radio-astronomy).
